name: Checkout Latest Release tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Release
      uses: actions/checkout@v2
    - name: commit id  
      run: git log --format="%H" -n 1
