---
name: Prereleased Workflow
on:
  release:
    types:
      - prereleased
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checking commit id
        run: git log --format="%H" -n 1
